---
- hosts: web
  tasks:
   - name: Update all Ubuntu packages
     apt:
       update_cache: yes
       cache_valid_time: 3600
   - name: Install JDK8 packages
     apt:
       name: openjdk-8-jdk
       state: present
   - name: Install Apache Maven
     apt:
       name: maven
       state: present
   - name: Install Git
     apt:
       name: git
       state: present
   - name: Clone a github repository
     git:
       repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
       dest: /home/nar/projects/
       clone: yes
       update: yes
   - name: Go to the folder
     command: chdir=/home/nar/projects/
   - name: Running mvn package
     shell: "mvn package"