---
- hosts: web
  tasks:
   - name: Update all Ubuntu packages
     apt:
       update_cache: yes
       cache_valid_time: 3600
   - name: Install JDK11 packages
     apt:
       name: openjdk-11-jdk
       state: present
   - name: Install Apache Maven
     apt:
       name: maven
       state: present
   - name: Install Git
     apt:
       name: git
       state: present
   - name: Clone a github repository
     git:
       repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
       dest: /home/nar/projects/
       clone: yes
       update: yes
   - name: Running mvn package
     command: mvn clean install
     args:
        chdir: /home/nar/projects/
- hosts: app
  become: yes
  tasks:
    - name: Update all Ubuntu packages
      apt:
         update_cache: yes
         cache_valid_time: 3600
    - name: Install JDK11 packages
      apt:
         name: openjdk-11-jdk
         state: present
    - name: Install Git
      apt:
         name: git
         state: present

    - name: Add group "Tomvat"
      group: name=tomcat

    - name: Add user "Tomcat"
      user: name=tomcat group=tomcat createhome=yes
      become: true

    - name: download & unarchive tomcat10
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.79/bin/apache-tomcat-9.0.79.tar.gz
        dest: /opt/tomcat9
        remote_src: no
        extra_opts: [--strip-components=1]

    - name: copy Tomcat
      copy: src=./apache-tomcat-9.0.79.tar.gz dest=/opt/apache-tomcat-9.0.79.tar.gz

    - name: Change ownership of Tomcat installation
      file: path=/opt/apache-tomcat-9.0.79 owner=tomcat group=tomcat state=directory recurse=yes

    - name: Configure Tomcat server
      template: src=server.xml dest=/opt/apache-tomcat-9.0.79/conf/

    - name: Configure Tomcat users
      template: src=tomcat-users.xml dest=/opt/apache-tomcat-9.0.79/conf/

    - name: Start Tomcat
      command: nohup /opt/apache-tomcat-9.0.79/bin/startup.sh
      become: true
      become_user: tomcat

    - name: wait for tomcat to start
      wait_for: port=8080