---
- hosts: web
  tasks:
   - name: Update all Ubuntu packages
     apt:
       update_cache: yes
       cache_valid_time: 3600
   - name: Install JDK8 packages
     apt:
       name: openjdk-8-jdk
       state: present
   - name: Install Apache Maven
     apt:
       name: maven
       state: present
   - name: Install Git
     apt:
       name: git
       state: present
   - name: Clone a github repository
     git:
       repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
       dest: /home/nar/projects/
       clone: yes
       update: yes
   - name: Running mvn package
     command: mvn clean install
     args:
        chdir: /home/nar/projects/
- hosts: app
  tasks:
    - name: Update all Ubuntu packages
      apt:
         update_cache: yes
         cache_valid_time: 3600
    - name: Install JDK8 packages
      apt:
         name: openjdk-8-jdk
         state: present
    - name: Install Git
      apt:
         name: git
         state: present
    - name: Create a Tomcat User
      user:
        name: tomcat
    - name: Create a Tomcat Group
      group:
        name: tomcat
    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat9
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes
    - name: Download & Unarchive Tomcat
      unarchive:
          src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.79/bin/apache-tomcat-9.0.79.tar.gz
          dest: /opt/tomcat9
          remote_src: yes
          extra_opts: [ --strip-components=1 ]
    - name: Change ownership of tomcat directory
      file:
          path: /opt/tomcat9
          owner: tomcat
          group: tomcat
          mode: "u+rwx,g+rx,o=rx"
          recurse: yes
          state: directory
    - name: Copy Tomcat service from local to remote
      copy:
         src: tomcat.service
         dest: /etc/systemd/system/
         mode: 0755
    - name: Start and Enable Tomcat 9 on sever
      systemd:
         name: tomcat
         state: started
         enabled: true
         daemon_reload: true
