---
- hosts: web
  tasks:
   - name: Update all Ubuntu packages
     apt:
       update_cache: yes
       cache_valid_time: 3600
   - name: Install JDK11 packages
     apt:
       name: openjdk-11-jdk
       state: present
   - name: Install Apache Maven
     apt:
       name: maven
       state: present
   - name: Install Git
     apt:
       name: git
       state: present
   - name: Clone a github repository
     git:
       repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
       dest: /home/nar/projects/
       clone: yes
       update: yes
   - name: Running mvn package
     command: mvn clean install
     args:
        chdir: /home/nar/projects/
- hosts: app
  become: yes
  tasks:
    - name: Update all Ubuntu packages
      apt:
         update_cache: yes
         cache_valid_time: 3600
    - name: Install JDK11 packages
      apt:
         name: openjdk-11-jdk
         state: present

    - name: Install Git
      apt:
         name: git
         state: present

    - name: Add user "Tomcat"
      user: name=tomcat createhome=yes
      become: true

    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat9
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes

    - name: download & unarchive tomcat9
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.79/bin/apache-tomcat-9.0.79.tar.gz
        dest: /opt/tomcat9
        remote_src: yes
        extra_opts: [ --strip-components=1 ]

    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat9
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Start Tomcat
      command: nohup /opt/tomcat9/bin/startup.sh
      become: true
      become_user: tomcat

    - name: wait for tomcat to start
      wait_for: port=8080

    - name: Transfer file from web to app
      synchronize:
        src: /home/nar/projects/target/hello-1.0.war
        dest: /opt/tomcat9/webapps/hello-1.0.war
      delegate_to: web