---
- hosts: web
  tasks:
   - name: Update all Ubuntu packages
     apt:
         update_cache: yes
         cache_valid_time: 3600
   - name: Install required Ubuntu packages
     apt:
         name: openjdk-8-jdk
         state: present
