                                                                                 role.yml                                                                                      Modified

---
- name: web-server configuration
  hosts: web
  become: yes

  roles:
   - common
   - webserver
   - security
- name: db configuration
  hosts: app
  become: yes

  roles:
   - common
   - security


